Repository LSSTDESC/CLMM, pull requests merged in 2019-11, with the labels that each got.

#179 Issue/77/lego pipeline remastered
  .gitignore
  examples/demo_pipeline.ipynb
Labels: priority

#171 Issue/170/cleaning notebooks
  clmm/plotting.py
  examples/demo_of_polaraveraging.ipynb
  examples/demo_polaraveraging.ipynb
  examples/demo_polaraveraging.py
Labels: good first issue, priority

#180 Issue/152/a bunch of small things
  .travis.yml
  CONTRIBUTING.md
  LICENSE
  clmm/__init__.py
  clmm/crypt/galaxycluster.py
  clmm/crypt/shear_azimuthal_averager.py
  docs/conf.py
  setup.py
  tests/crypt/old_test_extended_galaxycluster_methods.py
  tests/crypt/old_test_shear_azimuthal_averager.py
Labels: PR: Ready for Review

#181 Linter all the things
  .pylintrc
  clmm/__init__.py
  clmm/galaxycluster.py
  clmm/modeling.py
  clmm/plotting.py
  clmm/polaraveraging.py
  clmm/utils.py
  examples/demo_pipeline.ipynb
  examples/support/mock_data.py
  tests/test_modeling.py
Labels: PR: Ready for Review

#168 fixed gx bug; corrected some typos
  clmm/polaraveraging.py
  tests/test_polaraveraging.py
Labels: bug, good first issue

#185 Issue/156/consistent constants
  clmm/constants.py
  clmm/modeling.py
  docs/conf.py
Labels: PR: Ready for Review

#186 Issue/170/minor demo pipeline fix
  examples/demo_pipeline.ipynb
  examples/generate_mock_data.ipynb
  examples/import_mock_data_as_GalaxyCluster_object.ipynb
  examples/modeling_demo.ipynb
  examples/rewrite_shearAzimuthalAverager.ipynb
  examples/run_function_on_GalaxyCluster.ipynb
Labels: PR: Ready for Review

#194 Fix the YOLO test
  tests/data/radial_average_test_array.txt
  tests/test_utils.py
Labels: PR: Ready for Review, priority

#174 Issue/110/re refactor clmm api
  clmm/__init__.py
  clmm/lsst/__init__.py
  clmm/lsst/io.py
  clmm/lsst/load_clusters_with_gcr.py
  clmm/modeling.py
  examples/load_from_DC2.ipynb
  tests/test_load_clusters_with_gcr.py
  tests/test_modeling_addback.py
Labels: PR: Ready for Review

#195 Issue/189/autocompile notebooks
  .conda.yml
  .gitignore
  .readthedocs.yml
  .travis.yml
  CONTRIBUTING.md
  docs/.gitignore
  docs/Makefile
  docs/conf.py
  docs/doc-config.ini
  docs/rtd-requirements.txt
  docs/source/demo_of_polaraveraging.rst
  docs/source/demo_pipeline.rst
  docs/source/generate_mock_data.rst
  docs/source/index_body.rst
  docs/source/modeling_demo.rst
  examples/Example1_Fit_Halo_Mass_to_Shear_Catalog.ipynb
  examples/demo_generate_mock_cluster.ipynb
  examples/demo_modeling_functionality.ipynb
  examples/demo_polaraveraging_functionality.ipynb
Labels: PR: Ready for Review
