Repository LSSTDESC/CLMM, pull requests merged in 2020-04, with the labels that each got.

#255 Issue/252/gal_id_in_bins
  clmm/__init__.py
  clmm/polaraveraging.py
  clmm/utils.py
  examples/demo_polaraveraging_functionality.ipynb
  tests/test_polaraveraging.py
  tests/test_utils.py
Labels: PR: Ready for Review, priority

#264 Issue/262/hard coded range in modeling
  clmm/modeling.py
  tests/test_modeling.py
Labels: PR: Ready for Review

#261 Issue/247/doc overview
  CONTRIBUTING.md
  OVERVIEW.md
  README.md
  clmm/galaxycluster.py
Labels: PR: Ready for Review

#265 Issue/253/binning
  clmm/utils.py
  examples/demo_polaraveraging_functionality.ipynb
  tests/test_utils.py
Labels: PR: Ready for Review

#270 Issue/262/hard coded range in modeling
  clmm/modeling.py
  examples/demo_modeling_functionality.ipynb
  examples/modeling_cmp_numcosmo.ipynb
Labels: PR: Ready for Review

#271 add metadata to profile_table
  clmm/polaraveraging.py
  tests/test_polaraveraging.py
Labels: PR: Ready for Review

#266 Set shear and convergence to zero if source is in front of the lens
  clmm/modeling.py
  requirements.txt
  tests/test_modeling.py
Labels: PR: Ready for Review

#258 Issue/216/polaraverage dc2
  clmm/polaraveraging.py
  clmm/utils.py
  tests/test_utils.py
Labels: PR: Ready for Review, dc2, priority
